### ISSUE TITLE
Unable to use redis-brain via unix socket

### ISSUE THREAD

**Issue by dictvm** [hubotio/hubot-redis-brain#8] opened 2015-09-02 01:50 UTC
My environment requires I run redis via a unix socket, which is fully supported by the redis developers. However, I have so far failed to find a working REDIS_URL-string for this setup.

I have tried the following REDIS_URLs: 

```
export REDIS_URL=unix:///home/hubot/.redis/sock
export REDIS_URL=unix:/home/hubot/.redis/sock
export REDIS_URL=redis+socket:/home/hubot/.redis/sock
```

According to various Google searches, `export REDIS_URL=unix:/home/hubot/.redis/sock`should be the correct option.

Unfortunately, my hubot fails to connect to redis with any of these configurations, while redis itself is running perfectly fine :

```
$ redis-cli -s ~/.redis/sock
redis /home/hubot/.redis/sock>

$ redis-server --version
Redis server v=2.8.21 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=5d69a78d027f8932
```

During startup, hubot discovers the REDIS_URL (without performing any verification, I assume), but then does not nothing: 

```
2015-09-02 03:40:20.450492500 [Wed Sep 02 2015 03:40:20 GMT+0200 (CEST)] INFO hubot-redis-brain: Discovered redis from REDIS_URL environment variable
```

when in fact I should be able to see something like this during first startup: 

```
[...] Initializing new data for #{prefix} brain
```

At first I thought, I might simply lack the option to add the required prefix to a unix socket when using REDIS_URL. However, said prefix is meant to be optional and should default to "hubot", so I cannot imagine that this is the problem.

Any help is really appreciated. Thank you!

**Comment by michaelansel** [comment] 2015-09-02 17:42
Maybe hubot-redis-brain is misusing the redis module and causing it to always attempt a TCP connection?

Looks like this is the relevant code bit: https://github.com/NodeRedis/node_redis/blob/master/index.js#L1233-L1255

**Comment by technicalpickles** [comment] 2015-10-09 17:39
The problem is that this script parses the REDIS_URL to construct options to pass into `Redis.createClient`: https://github.com/hubot-scripts/hubot-redis-brain/blob/master/src/redis-brain.coffee#L38

I think it needs to check for a `unix` scheme, and pass in something different. Looking at https://github.com/NodeRedis/node_redis/blob/7922d4eb8552b287b30a18a744c9ab27674c12e5/index.js#L1140 I think the path to the socket is passed in as a string to 'port' (not sure how that makes sense).

**Comment by ChrisCinelli** [comment] 2015-11-30 07:48
It looks like that aw worked on this. I created a pull request: https://github.com/hubot-scripts/hubot-redis-brain/pull/12 - But I suggest #14 for more options

**Comment by ChrisCinelli** [comment] 2015-11-30 09:45
This should also fix it: https://github.com/hubot-scripts/hubot-redis-brain/pull/14

**Comment by law** [comment] 2016-01-23 10:00
I am also having these issues, would love to see #14 merged if it fixes the problem.

**Comment by elespike** [comment] 2017-05-04 15:20
@technicalpickles let's give hubot-redis-brain some love! I'd like to see #14 merged as well. Willing to help, if needed.

**Comment by mose** [comment] 2017-06-02 23:22
The #12 was merged (well, code was merged, PR was not, my fault). I tested locally and it works fine.

:heart: :heart: :heart:

**Closed as completed by mose** 2017-06-02 23:22 UTC
